name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.0.2
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  functional_data: ^1.0.0
  intl: ^0.17.0
  flutter_reactive_ble:
    git:
      url: https://github.com/Nanoleq/flutter_reactive_ble
      path: packages/flutter_reactive_ble
      ref: nano-1.0.2

  provider: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.4
  dependency_validator: ^3.1.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2

flutter:
  uses-material-design: true
