name: reactive_ble_desktop
description: A non official desktop implementation of flutter_reactive_ble for desktop relying on quick_blue
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  quick_blue: ^0.4.1+1
  reactive_ble_platform_interface:
    path: ../reactive_ble_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
